language: java
sudo: false
script: mvn clean package
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - oraclejdk8
  - oraclejdk9
env:
  - MAVEN=3.5.0
after_success:
  - bash <(curl -s https://codecov.io/bash)
